const aircrafts = [
  {
    id: 1,
    title: "Helicopter",
    fuel: "Gasoline",
    size: "Meidum",
    speed: "Normal",
    interiorColor: "Black",
    exteriorColor: "Black",
    image: "aircraft.jpg",
    price: 5000,
    milleage: 10,
    timeStamp: new Date(2013, 1, 3),
  },
  {
    id: 2,
    title: "Helicopter",
    fuel: "Electricity",
    size: "Small",
    speed: "Fast",
    interiorColor: "Red",
    exteriorColor: "Black",
    image: "aircraft.jpg",
    price: 250000,
    milleage: 0,
    timeStamp: new Date(2012, 1, 3),
  },
  {
    id: 3,
    title: "Paracopter",
    fuel: "Diesel",
    size: "Meidum",
    speed: "Normal",
    interiorColor: "Blue",
    exteriorColor: "Blue",
    image: "aircraft.jpg",
    price: 650000,
    milleage: 0,
    timeStamp: new Date(2014, 1, 3),
  },
  {
    id: 4,
    title: "Helicopter",
    fuel: "Kerosene",
    size: "Big",
    speed: "Slow",
    interiorColor: "Green",
    exteriorColor: "Black",
    image: "aircraft.jpg",
    price: 500000,
    milleage: 10,
    timeStamp: new Date(2015, 1, 3),
  },
  {
    id: 5,
    title: "Helicopter",
    fuel: "Gasoline",
    size: "Meidum",
    speed: "Normal",
    interiorColor: "Black",
    exteriorColor: "Red",
    image: "aircraft.jpg",
    price: 5000,
    milleage: 10,
    timeStamp: new Date(2017, 1, 3),
  },
  {
    id: 6,
    title: "Helicopter",
    fuel: "Gasoline",
    size: "Meidum",
    speed: "Normal",
    interiorColor: "Black",
    exteriorColor: "Black",
    image: "aircraft.jpg",
    price: 5000,
    milleage: 10,
    timeStamp: new Date(2017, 1, 3),
  },
  {
    id: 7,
    title: "Helicopter",
    fuel: "Gasoline",
    size: "Meidum",
    speed: "Normal",
    interiorColor: "Black",
    exteriorColor: "Black",
    image: "aircraft.jpg",
    price: 5000,
    milleage: 10,
    timeStamp: new Date(2017, 1, 3),
  },
  {
    id: 8,
    title: "Helicopter",
    fuel: "Gasoline",
    size: "Meidum",
    speed: "Normal",
    interiorColor: "Black",
    exteriorColor: "Black",
    image: "aircraft.jpg",
    price: 5000,
    milleage: 10,
    timeStamp: new Date(2017, 1, 3),
  },
  {
    id: 9,
    title: "Helicopter",
    fuel: "Gasoline",
    size: "Meidum",
    speed: "Normal",
    interiorColor: "Black",
    exteriorColor: "Black",
    image: "aircraft.jpg",
    price: 5000,
    milleage: 10,
    timeStamp: new Date(2017, 1, 3),
  },
];

export default aircrafts;
