const bikes = [
  {
    id: 1,
    title: "Harley",
    fuel: "Gasoline",
    transmission: "CVT",
    engine: "V Engine",
    finalDrive: "Belt",
    color: "Black",
    image: "bike.jpg",
    price: 5000,
    milleage: 10,
    timeStamp: new Date(2017, 0, 3),
  },
  {
    id: 2,
    title: "Harley",
    fuel: "Diesel",
    transmission: "Dual clutch",
    engine: "Inline",
    finalDrive: "Shaft",
    color: "Red",
    image: "bike.jpg",
    price: 15000,
    milleage: 0,
    timeStamp: new Date(2013, 0, 3),
  },
  {
    id: 3,
    title: "Yamaha",
    fuel: "Electricity",
    transmission: "Centrifugal Clutch",
    engine: "Single Cylinder",
    finalDrive: "Belt",
    color: "Green",
    image: "bike.jpg",
    price: 25000,
    milleage: 120,
    timeStamp: new Date(2018, 0, 3),
  },
  {
    id: 4,
    title: "Suzuki",
    fuel: "Kerosene",
    transmission: "CVT",
    engine: "V Engine",
    finalDrive: "Chain",
    color: "Blue",
    image: "bike.jpg",
    price: 205000,
    milleage: 0,
    timeStamp: new Date(2022, 0, 3),
  },
  {
    id: 5,
    title: "Harley",
    fuel: "Gasoline",
    transmission: "CVT",
    engine: "V Engine",
    finalDrive: "Belt",
    color: "Black",
    image: "bike.jpg",
    price: 5000,
    milleage: 10,
    timeStamp: new Date(2017, 0, 3),
  },
  {
    id: 6,
    title: "Harley",
    fuel: "Diesel",
    transmission: "Dual clutch",
    engine: "Inline",
    finalDrive: "Shaft",
    color: "Red",
    image: "bike.jpg",
    price: 15000,
    milleage: 0,
    timeStamp: new Date(2013, 0, 3),
  },
  {
    id: 7,
    title: "Yamaha",
    fuel: "Electricity",
    transmission: "Centrifugal Clutch",
    engine: "Single Cylinder",
    finalDrive: "Belt",
    color: "Green",
    image: "bike.jpg",
    price: 25000,
    milleage: 120,
    timeStamp: new Date(2018, 0, 3),
  },
  {
    id: 8,
    title: "Suzuki",
    fuel: "Kerosene",
    transmission: "CVT",
    engine: "V Engine",
    finalDrive: "Chain",
    color: "Blue",
    image: "bike.jpg",
    price: 205000,
    milleage: 0,
    timeStamp: new Date(2022, 0, 3),
  },
  {
    id: 9,
    title: "Harley",
    fuel: "Gasoline",
    transmission: "CVT",
    engine: "V Engine",
    finalDrive: "Belt",
    color: "Black",
    image: "bike.jpg",
    price: 5000,
    milleage: 10,
    timeStamp: new Date(2017, 0, 3),
  },
  {
    id: 10,
    title: "Harley",
    fuel: "Diesel",
    transmission: "Dual clutch",
    engine: "Inline",
    finalDrive: "Shaft",
    color: "Red",
    image: "bike.jpg",
    price: 15000,
    milleage: 0,
    timeStamp: new Date(2013, 0, 3),
  },
  {
    id: 11,
    title: "Yamaha",
    fuel: "Electricity",
    transmission: "Centrifugal Clutch",
    engine: "Single Cylinder",
    finalDrive: "Belt",
    color: "Green",
    image: "bike.jpg",
    price: 25000,
    milleage: 120,
    timeStamp: new Date(2018, 0, 3),
  },
  {
    id: 12,
    title: "Suzuki",
    fuel: "Kerosene",
    transmission: "CVT",
    engine: "V Engine",
    finalDrive: "Chain",
    color: "Blue",
    image: "bike.jpg",
    price: 205000,
    milleage: 0,
    timeStamp: new Date(2022, 0, 3),
  },
  {
    id: 13,
    title: "Harley",
    fuel: "Gasoline",
    transmission: "CVT",
    engine: "V Engine",
    finalDrive: "Belt",
    color: "Black",
    image: "bike.jpg",
    price: 5000,
    milleage: 10,
    timeStamp: new Date(2017, 0, 3),
  },
  {
    id: 14,
    title: "Harley",
    fuel: "Diesel",
    transmission: "Dual clutch",
    engine: "Inline",
    finalDrive: "Shaft",
    color: "Red",
    image: "bike.jpg",
    price: 15000,
    milleage: 0,
    timeStamp: new Date(2013, 0, 3),
  },
  {
    id: 15,
    title: "Yamaha",
    fuel: "Electricity",
    transmission: "Centrifugal Clutch",
    engine: "Single Cylinder",
    finalDrive: "Belt",
    color: "Green",
    image: "bike.jpg",
    price: 25000,
    milleage: 120,
    timeStamp: new Date(2018, 0, 3),
  },
  {
    id: 16,
    title: "Suzuki",
    fuel: "Kerosene",
    transmission: "CVT",
    engine: "V Engine",
    finalDrive: "Chain",
    color: "Blue",
    image: "bike.jpg",
    price: 205000,
    milleage: 0,
    timeStamp: new Date(2022, 0, 3),
  },
];

export default bikes;
