const cars = [
  {
    id: 1,
    title: "Toyota",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 2,
    title: "Nissan",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 3,
    title: "Mazda",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 4,
    title: "Citroen",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 5,
    title: "BMW",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 6,
    title: "Toyota",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 7,
    title: "Nissan",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 8,
    title: "Mazda",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 9,
    title: "Citroen",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 10,
    title: "BMW",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 11,
    title: "Toyota",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 12,
    title: "Nissan",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 13,
    title: "Mazda",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 14,
    title: "Citroen",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 15,
    title: "BMW",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 16,
    title: "Toyota",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 17,
    title: "Nissan",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 18,
    title: "Mazda",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 19,
    title: "Citroen",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
  {
    id: 20,
    title: "BMW",
    fuel: "Gasoline",
    transmission: "Automatic CTV",
    engine: "2.4: H4 16V GDI DOHC Turbo",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: "5000$",
    milleage: 0,
  },
];

export default cars;
