const cars = [
  {
    id: 1,
    title: "Toyota",
    fuel: "Gasoline",
    transmission: "Automatic",
    engine: "Naturally aspirated",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 5000,
    milleage: 10,
    timeStamp: new Date(2017, 0, 3),
  },
  {
    id: 2,
    title: "Nissan",
    fuel: "Gasoline",
    transmission: "CVT",
    engine: "Naturally aspirated",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 35000,
    milleage: 50,
    timeStamp: new Date(2017, 0, 3),
  },
  {
    id: 3,
    title: "Mazda",
    fuel: "Gasoline",
    transmission: "Manual",
    engine: "Naturally aspirated",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 55000,
    milleage: 500,
    timeStamp: new Date(2017, 0, 3),
  },
  {
    id: 4,
    title: "Citroen",
    fuel: "Gasoline",
    transmission: "Automatic",
    engine: "Naturally aspirated",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 15000,
    milleage: 1000,
    timeStamp: new Date(2017, 0, 3),
  },
  {
    id: 5,
    title: "BMW",
    fuel: "Gasoline",
    transmission: "Manual",
    engine: "Naturally aspirated",
    drivetrain: "Rear-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 155000,
    milleage: 1230,
    timeStamp: new Date(2019, 5, 8),
  },
  {
    id: 6,
    title: "Toyota",
    fuel: "Gasoline",
    transmission: "Automatic",
    engine: "Naturally aspirated",
    drivetrain: "Rear-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 255000,
    milleage: 31240,
    timeStamp: new Date(2019, 5, 8),
  },
  {
    id: 7,
    title: "Nissan",
    fuel: "Gasoline",
    transmission: "CVT",
    engine: "Naturally aspirated",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Red",
    price: 355000,
    milleage: 21340,
    timeStamp: new Date(2019, 5, 8),
  },
  {
    id: 8,
    title: "Mazda",
    fuel: "Gasoline",
    transmission: "Automatic",
    engine: "Naturally aspirated",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Red",
    price: 10000,
    milleage: 1230,
    timeStamp: new Date(2019, 5, 8),
  },
  {
    id: 9,
    title: "Citroen",
    fuel: "Gasoline",
    transmission: "CVT",
    engine: "Naturally aspirated",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Blue",
    price: 20000,
    milleage: 0,
    timeStamp: new Date(2019, 5, 8),
  },
  {
    id: 10,
    title: "BMW",
    fuel: "Gasoline",
    transmission: "Automatic",
    engine: "Naturally aspirated",
    drivetrain: "All-wheel Drive",
    interiorColor: "Green",
    exteriorColor: "Black",
    price: 34000,
    milleage: 0,
    timeStamp: new Date(2010, 3, 5),
  },
  {
    id: 11,
    title: "Toyota",
    fuel: "Diesel",
    transmission: "Automatic",
    engine: "Naturally aspirated",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 56000,
    milleage: 0,
    timeStamp: new Date(2010, 3, 5),
  },
  {
    id: 12,
    title: "Nissan",
    fuel: "Electricity",
    transmission: "Automatic",
    engine: "Naturally aspirated",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 5000,
    milleage: 0,
    timeStamp: new Date(2017, 0, 3),
  },
  {
    id: 13,
    title: "Mazda",
    fuel: "Gasoline",
    transmission: "Automatic",
    engine: "Turbocharged",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 5000,
    milleage: 0,
    timeStamp: new Date(2010, 3, 5),
  },
  {
    id: 14,
    title: "Citroen",
    fuel: "Gasoline",
    transmission: "Automatic",
    engine: "CRDi",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 500000,
    milleage: 0,
    timeStamp: new Date(2010, 3, 5),
  },
  {
    id: 15,
    title: "BMW",
    fuel: "Kerosene",
    transmission: "Automatic",
    engine: "Naturally aspirated",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 8000,
    milleage: 0,
    timeStamp: new Date(2010, 3, 5),
  },
  {
    id: 16,
    title: "Toyota",
    fuel: "Gasoline",
    transmission: "Automatic",
    engine: "MPFI",
    drivetrain: "Front-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 5000,
    milleage: 0,
    timeStamp: new Date(2013, 8, 3),
  },
  {
    id: 17,
    title: "Nissan",
    fuel: "Gasoline",
    transmission: "CVT",
    engine: "Naturally aspirated",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 5000,
    milleage: 0,
    timeStamp: new Date(2013, 8, 3),
  },
  {
    id: 18,
    title: "Mazda",
    fuel: "Gasoline",
    transmission: "Automatic",
    engine: "Trubocharged",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 5000,
    milleage: 0,
    timeStamp: new Date(2013, 8, 3),
  },
  {
    id: 19,
    title: "Citroen",
    fuel: "Gasoline",
    transmission: "Automatic",
    engine: "Naturally aspirated",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 5000,
    milleage: 0,
    timeStamp: new Date(2013, 8, 3),
  },
  {
    id: 20,
    title: "BMW",
    fuel: "Gasoline",
    transmission: "Automatic",
    engine: "Naturally aspirated",
    drivetrain: "All-wheel Drive",
    interiorColor: "Black",
    exteriorColor: "Black",
    price: 5000,
    milleage: 0,
    timeStamp: new Date(2013, 8, 3),
  },
];

export default cars;
