import Head from "next/head";
import React from "react";
import { ReactNode } from "react";
import Image from "next/image";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Filter from "./Filter";
import Order from "./Order";
import PaginationElement from "./Pagination";
import { useRouter } from "next/router";
import { Badge } from "@mui/material";
import Link from "next/link";
import { useAppSelector } from "@/redux/store";

interface IProps {
  children?: ReactNode;
}

export default function Layout({ children }: IProps) {
  const router = useRouter();

  const cartItems = useAppSelector((state) => state.cart.cart.length);

  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full min-h-screen bg-neutral-900 pt-8 scroll-smooth font-primary">
        <h1 className="text-center lg:text-9xl text-5xl text-rose-500 font-bold uppercase animate-in fade-in duration-1000 ">
          Vehicle Shop
        </h1>
        <Link
          href={"/cart"}
          className="absolute top-10 right-10 cursor-pointer hover:bg-neutral-800 p-1 rounded-md"
        >
          <Badge badgeContent={cartItems} color="primary">
            <Image src="/cart.svg" alt="error" width={40} height={40} />
          </Badge>
        </Link>
        <div className="pt-20 pb-20 animate-in fade-in duration-1000">
          <Navbar />
          <div className="flex justify-center mt-8">
            <Filter />
            <main className="w-8/12 2xl:w-6/12 border-l border-r border-b rounded-md border-neutral-800 h-fit">
              {children}
            </main>
            <Order />
          </div>
          <PaginationElement key={router.asPath} />
          <Footer />
        </div>
      </div>
    </>
  );
}
