import Head from "next/head";
import { ReactNode } from "react";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Filter from "./Filter";
import Order from "./Order";
import PaginationElement from "./Pagination";

interface IProps {
  children?: ReactNode;
}

export default function Layout({ children }: IProps) {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full min-h-screen bg-neutral-900 pt-8">
        <h1 className="text-center text-9xl text-rose-600 font-mono font-bold uppercase">
          Car Shop
        </h1>
        <div className="pt-20 pb-20">
          <Navbar />
          <div className="flex  justify-center">
            <Filter />
            <main className="w-6/12 border-b border-l border-r rounded-b-md border-neutral-800 h-fit p-0">
              {children}
            </main>
            <Order />
          </div>
          <PaginationElement />
          <Footer />
        </div>
      </div>
    </>
  );
}
